Create default asp net core app
ImplementLife/Cinema pull request #3
Opened 2022-10-08 11:24 UTC by AmateurBoy

I have created a default application where we will be adding features.
![image](https://user-images.githubusercontent.com/90874301/194705038-aca530ea-09cd-442d-85ee-b887e3aadea0.png)

2022-10-08 11:43 UTC, ImplementLife commented
Good job) I'll look later)

2022-10-10 10:06 UTC, ImplementLife requested changes
Delete all files in the 'wwwroot' folder

2022-10-10 11:07 UTC, AmateurBoy commented
Ok

2022-10-10 11:09 UTC, ImplementLife approved these changes
Good)

2022-10-10 11:10 UTC, merged